### ISSUE TITLE
prometheus-tuxedo-exporter issues while running

### ISSUE THREAD

**Issue by viji97** [aivarsk/prometheus-tuxedo-exporter#1]
Hi Aivarsk,

I am trying to install the promotheus tuxedo exporter.. while running below command getting below issue:
Traceback (most recent call last):
  File "/usr/bin/prometheus-tuxedo-exporter.py", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
**pkg_resources.DistributionNotFound: prometheus-client>=0.8.0**

**Comment by aivarsk** [comment]
You should be running Python3 not Python2.7 (/usr/lib/python2.7 in the exception backtrace)

**Comment by viji97** [comment]
Thanks for your quick response.. After uninstall python2.7 and installed python3.6 version, I got different errors:

Traceback (most recent call last):
  File "/usr/local/bin/prometheus-tuxedo-exporter.py", line 4, in <module>
    __import__('pkg_resources').run_script('prometheus-tuxedo-exporter==1.0.1', 'prometheus-tuxedo-exporter.py')
  File "/home/a596845/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/a596845/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/prometheus_tuxedo_exporter-1.0.1-py3.6.egg/EGG-INFO/scripts/prometheus-tuxedo-exporter.py", line 6, in <module>
    import tuxedo as t
ModuleNotFoundError: No module named 'tuxedo

When I try to install tuxedo module using below command, another error-
pip3 install tuxedo
https://files.pythonhosted.org/packages/a0/3a/065a6538472c35b48860bc8b15be574d786708d0f85401e886891d814f05/tuxedo-1.0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bchxb_8i/tuxedo/setup.py", line 29, in <module>
        os.path.join(os.environ['TUXDIR'], 'include'),
      File "/usr/lib64/python3.6/os.py", line 669, in __getitem__
        raise KeyError(key) from None
    KeyError: 'TUXDIR'

**Comment by aivarsk** [comment]
export TUXDIR=/path/to/Tuxedo/installation

**Comment by viji97** [comment]
Thanks Aivars Kalvans..
I have resolved the above issues, but still I am facing below issue while installing tuxedo using python - pip3 install tuxedo.

some of the tuxedo lib's are 32 bit version, but gcc is running -m64 which is 64 bit version. Is there way to set FLAG -m32 instead of -m64 at runtime dynamiccaly?

running install
    running build
    running build_ext
    creating tmp
    **gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c /tmp/tmpwz3vl1y7.cpp -o tmp/tmpwz3vl1y7.o -std=c++17
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c /tmp/tmp5_c2x4mk.cpp -o tmp/tmp5_c2x4mk.o -fvisibility=hidden**
    building 'tuxedo' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    **gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DTUXEDO_WSC=0 -I/tuxedo/home/tuxedo12.2.2.0.0/include -I/usr/local/lib/python3.6/site-packages/pybind11/include -I/usr/local/lib/python3.6/site-packages/pybind11/include -I/usr/include/python3.6m -c src/tuxedo.cpp -o build/temp.linux-x86_64-3.6/src/tuxedo.o -DVERSION_INFO="1.0.7" -std=c++17 -fvisibility=hidden**
    creating build/lib.linux-x86_64-3.6
    g++ -pthread -shared -Wl,-z,relro -g build/temp.linux-x86_64-3.6/src/tuxedo.o -L/tuxedo/home/tuxedo12.2.2.0.0/lib -L/usr/lib64 -ltux -lfml32 -ltmib -lengine -lpython3.6m -o build/lib.linux-x86_64-3.6/tuxedo.cpython-36m-x86_64-linux-gnu.so
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libtux.so when searching for -ltux
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libtux.a when searching for -ltux
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -ltux
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libfml32.so when searching for -lfml32
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libfml32.a when searching for -lfml32
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lfml32
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libtmib.so when searching for -ltmib
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libtmib.a when searching for -ltmib
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -ltmib
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libengine.so when searching for -lengine
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libengine.a when searching for -lengine
    /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lengine
    **collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1**

**Comment by aivarsk** [comment]
Something like:
`CFLAGS=-m32 python3 setup.py build`
or
`CFLAGS=-m64 python3 setup.py build`

should compile the 32bit or 64bit version assuming you have the Tuxedo and Python installed for the desired bit  count. But I will check that when I have time for it. What is the reason for using 32bit Tuxedo on a 64bit OS?

**Comment by viji97** [comment]
I am getting error while installing the python tuxedo package on RHEL7 server. Can you please help me to resolve this issue. The issue is gcc command invoked by pip3 when we try to install tuxedo package, uses -m64 flag by default. anyone know how to pass/set -m32 to this command ? 

running install
running build
running build_ext
creating tmp
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c /tmp/tmpwz3vl1y7.cpp -o tmp/tmpwz3vl1y7.o -std=c++17
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c /tmp/tmp5_c2x4mk.cpp -o tmp/tmp5_c2x4mk.o -fvisibility=hidden
building 'tuxedo' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DTUXEDO_WSC=0 -I/tuxedo/home/tuxedo12.2.2.0.0/include -I/usr/local/lib/python3.6/site-packages/pybind11/include -I/usr/local/lib/python3.6/site-packages/pybind11/include -I/usr/include/python3.6m -c src/tuxedo.cpp -o build/temp.linux-x86_64-3.6/src/tuxedo.o -DVERSION_INFO="1.0.7" -std=c++17 -fvisibility=hidden
creating build/lib.linux-x86_64-3.6
g++ -pthread -shared -Wl,-z,relro -g build/temp.linux-x86_64-3.6/src/tuxedo.o -L/tuxedo/home/tuxedo12.2.2.0.0/lib -L/usr/lib64 -ltux -lfml32 -ltmib -lengine -lpython3.6m -o build/lib.linux-x86_64-3.6/tuxedo.cpython-36m-x86_64-linux-gnu.so
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libtux.so when searching for -ltux
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libtux.a when searching for -ltux
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -ltux
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libfml32.so when searching for -lfml32
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libfml32.a when searching for -lfml32
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lfml32
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libtmib.so when searching for -ltmib
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libtmib.a when searching for -ltmib
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -ltmib
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libengine.so when searching for -lengine
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /tuxedo/home/tuxedo12.2.2.0.0/lib/libengine.a when searching for -lengine
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lengine
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status


after that tried with this command: **CFLAGS=-m32 python3 setup.py build**

running build
running build_ext
gcc -pthread -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -m32 -fPIC -I/usr/include/python3.6m -c /tmp/tmp4_3v52en.cpp -o tmp/tmp4_3v52en.o -std=c++17
gcc -pthread -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -m32 -fPIC -I/usr/include/python3.6m -c /tmp/tmpfhl2yycg.cpp -o tmp/tmpfhl2yycg.o -fvisibility=hidden
building 'tuxedo' extension
gcc -pthread -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -m32 -fPIC -DTUXEDO_WSC=0 -I/tuxedo/home/tuxedo12.2.2.0.0/include -I/usr/local/lib/python3.6/site-packages/pybind11/include -I/usr/local/lib/python3.6/site-packages/pybind11/include -I/usr/include/python3.6m -c src/tuxedo.cpp -o build/temp.linux-x86_64-3.6/src/tuxedo.o -DVERSION_INFO="1.0.7" -std=c++17 -fvisibility=hidden
In file included from /usr/include/python3.6m/Python.h:8,
                 from /usr/local/lib/python3.6/site-packages/pybind11/include/pybind11/detail/common.h:124,
                 from /usr/local/lib/python3.6/site-packages/pybind11/include/pybind11/pytypes.h:12,
                 from /usr/local/lib/python3.6/site-packages/pybind11/include/pybind11/cast.h:13,
                 from /usr/local/lib/python3.6/site-packages/pybind11/include/pybind11/attr.h:13,
                 from /usr/local/lib/python3.6/site-packages/pybind11/include/pybind11/pybind11.h:45,
                 from /usr/local/lib/python3.6/site-packages/pybind11/include/pybind11/functional.h:12,
                 from src/tuxedo.cpp:29:
**/usr/include/python3.6m/pyconfig.h:4:10: fatal error: pyconfig-32.h: No such file or directory
    4 | #include "pyconfig-32.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1**
